FROM node:18-alpine

# Set working directory
WORKDIR /app

# Install system packages for code execution
RUN apk add --no-cache g++ gcc make python3 python3-dev

# Copy files
COPY package*.json ./
RUN npm install
COPY . .

# Expose port and start app
EXPOSE 5000
CMD ["npm", "start"]
